REM INSERTING into contestant
SET DEFINE OFF;
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-001','Sherine Devi Sutomo','SMA Harapan Bangsa');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-002','Renaldi','SMK TARUNA BHAKTI DEPOK');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-003','Daniel ','SMK Prestasi Prima ');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-004','Dian Prayogo','SMKN 25 Jakarta Selatan');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-005','Gunawan','SMA SINAR DHARMA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-006','Bayu Prasetyo','SMK Plus Al-Musyarrofah');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-007','Geerhan Sentanu','SMAN 2 JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-008','Ricky Raven','PELITA IV');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-009','I Gusti Putu Aditya','SMK Telkom Jakarta');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-010','David Honasan','SMA Bunda Hati Kudus');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-011','Ryan Andrian','SMA Kristen Kanaan');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-012','Alberts Febrian Prawira','SMA DHARMA SUCI');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-013','Aris Setyadji Pamungkas','SMAN 14 Kota Tangerang');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-014','Steven Jonathan','SMA Candra Naya');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-015','Rizky Maulana Yatim','SMK LABORATORIUM JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-016','Andrean Lay','Sekolah Cinta Kasih Tzu Chi');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-017','Try Hartono','SMA Dharma Putra Tangerang');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-018','Taufiq Safri Nando','SMK Negeri 6 Jakarta ');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-019','Muhamad Saepuloh','SMK Nusantara Raya Bandung');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-020','Muhammad Rifqi P','SMK Bonavita Tangerang');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-021',' Muhammad Cholis Malik','SMK N 26 JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-022','Amadeus Ryo Luchen','SMA Budi Mulia');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-023','Handoko','SMK NEGERI 7 JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-024','DAFFA ASLAM MULTAZAM','SMKN 2 KOTA TANGERANG SELATAN');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-025','EMAN SULAEMAN','SMK NEGERI 1 RANGKASBITUNG');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-026','HANDOKO ','SMK BINA CITRA ASIA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-027','Achmad Kurnia Khairawan','SMK Negeri 30');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-028','Muhammad Rizky Fauzi','SMK Negeri 4 Bandung');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-029','Kristi Handayani','SMA PERMAI');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-030','Hosea Jovian Satria Adhi Perdana','SMAK PENABUR GADING SERPONG');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-031','Wildan Fajriansyah','SMK PRAKARYA INTERNASIONAL');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-032','GENNESARET KHARISTIO','SMAK 1 PENABUR JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-033','Chynthia','SMK Pancaran Berkat');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-034','Dewi Angriani','SMA Pancaran Berkat');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-035','Putra Utomo Cemerlang','SMK Farmasi BPK PENABUR');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-036','Maverick Jonathan','SMAK 7 PENABUR');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-037','Kevin Jonar','SMA Pusaka Abadi');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-038','Rully Ardiansyah','SMAN 11 Kab. Tangerang');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-039','Danendra Lohanata','SMA Harapan Bangsa');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-040','Ervan Antonius','SMK TARUNA BHAKTI DEPOK');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-041','Deny','SMK Prestasi Prima ');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-042','Muhammad Ramadhan','SMKN 25 Jakarta Selatan');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-043','Febry Gohandy','SMA SINAR DHARMA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-044','Diffa Muhammad Risqullah','SMK Plus Al-Musyarrofah');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-045','Ryo Kenrie Wongso','SMAN 2 JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-046','Oktavianus','PELITA IV');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-047','Fatahillah','SMK Telkom Jakarta');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-048','Jason','SMA Bunda Hati Kudus');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-049','Jessica','SMA Kristen Kanaan');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-050','Irvin Delano','SMA DHARMA SUCI');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-051','Mohammad Anthoni','SMAN 14 Kota Tangerang');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-052','Vincent Sandrya','SMA Candra Naya');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-053','Farhan Agustian','SMK LABORATORIUM JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-054','Donny Wiselee','Sekolah Cinta Kasih Tzu Chi');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-055','Richard Alison','SMA Dharma Putra Tangerang');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-056','M. Rafli Ali','SMK Negeri 6 Jakarta ');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-057','Wisnu Abdilah','SMK Nusantara Raya Bandung');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-058','Muhammad Ichiro L','SMK Bonavita Tangerang');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-059','Rian Priyanto','SMK N 26 JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-060','Teodorus Nathaniel','SMA Budi Mulia');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-061','Samsul Anwar','SMK NEGERI 7 JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-062','IQBAL RAMADHAN','SMKN 2 KOTA TANGERANG SELATAN');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-063','MUHAMMAD ALFIAN NURFAIZ','SMK NEGERI 1 RANGKASBITUNG');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-064','ISWAN NANDA','SMK BINA CITRA ASIA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-065','Putra Rizky Gumelar','SMK Negeri 30');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-066','Christian Marchelino','SMA Cinta Kasih Tzu Chi');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-067','Dede Rusliandi Taruna','SMK Negeri 4 Bandung');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-068','Ricky','SMA PERMAI');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-069','Randy Christian Saputra','SMAK PENABUR GADING SERPONG');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-070','Muhamad Raffi Hidayatullah','SMK PRAKARYA INTERNASIONAL');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-071','JASON YONATHAN HUANG','SMAK 1 PENABUR JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-072','Felisiana','SMK Pancaran Berkat');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-073','Jimmy Zuliansyah','SMA Pancaran Berkat');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-074','Devina Atmanegara','SMK Farmasi BPK PENABUR');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-075','Rico Filberto','SMAK 7 PENABUR');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-076','Adrian Ananda','SMA Pusaka Abadi');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-077','Rizki Budi Prasetyo','SMAN 11 Kab. Tangerang');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-078','Kevin Widjaja','SMA Harapan Bangsa');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-079','Syahrifal Anwar','SMK TARUNA BHAKTI DEPOK');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-080','Agung','SMK Prestasi Prima ');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-081','Aji Reza Mahendra','SMKN 25 Jakarta Selatan');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-082','Winalton','SMA SINAR DHARMA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-083','Hanifi Yudistira','SMK Plus Al-Musyarrofah');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-084','Prajna Prasetya','SMAN 2 JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-085','Kevin Agustin','PELITA IV');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-086','Fardika Rais Hidayatullah','SMK Telkom Jakarta');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-087','Wisnu','SMA Bunda Hati Kudus');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-088','Dea Novia','SMA Kristen Kanaan');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-089','James Wesley','SMA DHARMA SUCI');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-090','Randy Dwi Chandra Sinatra','SMAN 14 Kota Tangerang');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-091','Chandra Wijaya','SMA Candra Naya');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-092','Joko Dwi Giyantoro','SMK LABORATORIUM JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-093',' Ryan Siautama','Sekolah Cinta Kasih Tzu Chi');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-094','Sevtian Ferdian','SMA Dharma Putra Tangerang');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-095','Annisa Ayu Pertiwi','SMK Negeri 6 Jakarta ');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-096','Ade Priatna','SMK Nusantara Raya Bandung');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-097','Heizell Septianus','SMK Bonavita Tangerang');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-098','Dodi Prasetyo','SMK N 26 JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-099','Ching Wen','SMA Budi Mulia');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-100','Harun Al Rasyid','SMK NEGERI 7 JAKARTA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-101','AHMAD RIZKY YUDHOYONO','SMKN 2 KOTA TANGERANG SELATAN');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-102','ASEP MIFAHUDIN','SMK NEGERI 1 RANGKASBITUNG');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-103','AZHAR ASHILAH','SMK BINA CITRA ASIA');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-104','Andhika Septiyadi','SMK Negeri 30');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-105','Brillian Fahmi Fauzi Perdana','SMK Negeri 4 Bandung');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-106','Andrew','SMA PERMAI');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-107','Jerrell Ezralemuel','SMAK PENABUR GADING SERPONG');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-108','Arpan Apriyana','SMK PRAKARYA INTERNASIONAL');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-109','Valen A','SMK Pancaran Berkat');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-110','David Stevanus','SMA Pancaran Berkat');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-111','Adeline Theophilia','SMK Farmasi BPK PENABUR');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-112','Kevin William','SMAK 7 PENABUR');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-113','Harry Setiawan','SMA Pusaka Abadi');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-114','Additional 1','Additional School 1');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-115','Additional 2','Additional School 2');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-116','Additional 3','Additional School 3');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-117','Additional 4','Additional School 4');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-118','Additional 5','Additional School 5');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-119','Additional 6','Additional School 6');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-120','Additional 7','Additional School 7');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-121','Additional 8','Additional School 8');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-122','Additional 9','Additional School 9');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-123','Additional 10','Additional School 10');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-124','Additional 11','Additional School 11');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-125','Additional 12','Additional School 12');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-126','Additional 13','Additional School 13');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-127','Additional 14','Additional School 14');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-128','Additional 15','Additional School 15');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-129','Additional 16','Additional School 16');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-130','Additional 17','Additional School 17');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-131','Additional 18','Additional School 18');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-132','Additional 19','Additional School 19');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-133','Additional 20','Additional School 20');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-134','Additional 21','Additional School 21');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-135','Additional 22','Additional School 22');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-136','Additional 23','Additional School 23');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-137','Additional 24','Additional School 24');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-138','Additional 25','Additional School 25');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-139','Additional 26','Additional School 26');
Insert into "contestant" (NAME_CODE,NAME,SCHOOL) values ('sql-140','Additional 27','Additional School 27');
